In [1]:
import torch
print(torch.__version__)

2.9.1+cpu


In [3]:
if torch.cuda.is_available():
    print("GPU is available")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available")

GPU not available


**Creating Tenors**

In [5]:
#empty tensor
a = torch.empty((2,3))
type(a)

torch.Tensor

In [6]:
#zero tensor
torch.zeros((3,2))

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [7]:
#one tensor
torch.ones((3,3))

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [8]:
#random tensor
torch.rand((2,2))

tensor([[0.3977, 0.5008],
        [0.6522, 0.2054]])

In [9]:
#manual_seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [10]:
#using tensor
torch.tensor([[2,4,6],[1,3,5]])

tensor([[2, 4, 6],
        [1, 3, 5]])

In [14]:
#arange
print(torch.arange(0,10,2))

#linspace
print(torch.linspace(0,10,5))

#identity(eye)
print(torch.eye(3))

#scalar fill 
print(torch.full((2,4),3))

tensor([0, 2, 4, 6, 8])
tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tensor([[3, 3, 3, 3],
        [3, 3, 3, 3]])


**Tensor Shapes**

In [15]:
x = torch.tensor([[2,4,6],[1,3,5]])
x.shape

torch.Size([2, 3])

In [16]:
torch.empty_like(x)

tensor([[3355409844976,             0,             0],
        [            0,             0,             0]])

In [17]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [18]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [19]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

**Tensor Data Types**

In [20]:
x.dtype

torch.int64

In [22]:
#convert to float32
torch.tensor([[2,4,6],[1,3,5]], dtype=torch.float32)

tensor([[2., 4., 6.],
        [1., 3., 5.]])

In [24]:
#using to()
x.to(torch.int32)

tensor([[2, 4, 6],
        [1, 3, 5]], dtype=torch.int32)

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |

**Mathematical Operations on Tensors**

**1.Scalar Operations**

In [25]:
x = torch.rand((2,3))
x

tensor([[0.7118, 0.7876, 0.4183],
        [0.9014, 0.9969, 0.7565]])

tensor([[2.7118, 2.7876, 2.4183],
        [2.9014, 2.9969, 2.7565]])
tensor([[-1.2882, -1.2124, -1.5817],
        [-1.0986, -1.0031, -1.2435]])
tensor([[2.1353, 2.3627, 1.2549],
        [2.7042, 2.9907, 2.2695]])
tensor([[0.1424, 0.1575, 0.0837],
        [0.1803, 0.1994, 0.1513]])
tensor([[23.7255, 26.2527, 13.9435],
        [30.0472, 33.2295, 25.2172]])
tensor([[0.7118, 0.7876, 0.4183],
        [0.9014, 0.9969, 0.7565]])
tensor([[0.5066, 0.6203, 0.1750],
        [0.8125, 0.9938, 0.5723]])


In [32]:
a = torch.rand((2,2))
b = torch.rand((2,2))
print(a)
print(b)

tensor([[0.7445, 0.4892],
        [0.2426, 0.7003]])
tensor([[0.5277, 0.2472],
        [0.7909, 0.4235]])


**2. Element wise Operations**

In [33]:
#element wise

print(a + b) #add
print(a - b) #subtract
print(a * b) #multiply
print(a / b) #divide
print(a ** b) #power
print(a % b) # modulo


tensor([[1.2722, 0.7364],
        [1.0334, 1.1238]])
tensor([[ 0.2168,  0.2420],
        [-0.5483,  0.2769]])
tensor([[0.3929, 0.1209],
        [0.1918, 0.2966]])
tensor([[1.4108, 1.9791],
        [0.3067, 1.6537]])
tensor([[0.8558, 0.8380],
        [0.3262, 0.8600]])
tensor([[0.2168, 0.2420],
        [0.2426, 0.2769]])


In [36]:
c = torch.tensor([[1,-2,0.5],[-2,9,-1.3]])
c

tensor([[ 1.0000, -2.0000,  0.5000],
        [-2.0000,  9.0000, -1.3000]])

In [40]:
torch.abs(c)

tensor([[1.0000, 2.0000, 0.5000],
        [2.0000, 9.0000, 1.3000]])

In [41]:
torch.neg(c)

tensor([[-1.0000,  2.0000, -0.5000],
        [ 2.0000, -9.0000,  1.3000]])

In [42]:
torch.round(c)

tensor([[ 1., -2.,  0.],
        [-2.,  9., -1.]])

In [43]:
torch.ceil(c)

tensor([[ 1., -2.,  1.],
        [-2.,  9., -1.]])

In [44]:
torch.floor(c)

tensor([[ 1., -2.,  0.],
        [-2.,  9., -2.]])

In [45]:
torch.clamp(c, min=2, max=3)

tensor([[2., 2., 2.],
        [2., 3., 2.]])

**3.Reduce Operations**

In [46]:
d = torch.randint(size = (2,3), low=0, high=10, dtype=torch.float64)
d

tensor([[4., 0., 5.],
        [7., 5., 9.]], dtype=torch.float64)

In [48]:
print(torch.sum(d)) # entire tensor
print(torch.sum(d, dim = 0)) # column wise sum
print(torch.sum(d, dim = 1)) # row wise sum

tensor(30., dtype=torch.float64)
tensor([11.,  5., 14.], dtype=torch.float64)
tensor([ 9., 21.], dtype=torch.float64)


In [50]:
print(torch.mean(d)) # entire tensor
print(torch.mean(d, dim = 0)) # column wise mean
print(torch.mean(d, dim = 1)) # row wise mean

tensor(5., dtype=torch.float64)
tensor([5.5000, 2.5000, 7.0000], dtype=torch.float64)
tensor([3., 7.], dtype=torch.float64)


In [53]:
print(torch.median(d)) # entire tensor

tensor(5., dtype=torch.float64)


In [54]:
print(torch.min(d)) 
print(torch.max(d))

tensor(0., dtype=torch.float64)
tensor(9., dtype=torch.float64)


In [55]:
torch.diff(d)

tensor([[-4.,  5.],
        [-2.,  4.]], dtype=torch.float64)

In [62]:
e = torch.randint(size=(2,3),low=1,high=10,dtype=torch.float32)
e

tensor([[1., 1., 4.],
        [6., 6., 6.]])

In [ ]:
torch.prod(e) #product of tensor elements

tensor(864.)

In [ ]:
torch.std(e) #standard deviation

tensor(2.4495)

In [66]:
torch.var(e) #variance of tensor

tensor(6.)

**4. Matrix Operations**

In [67]:
f = torch.randint(size=(2,3), low=1, high=10)
g = torch.randint(size=(3,2),low=1, high=20)
print(f)
print(g)

tensor([[1, 4, 1],
        [3, 7, 2]])
tensor([[ 7,  7],
        [ 4,  2],
        [12,  7]])


In [68]:
torch.matmul(f, g)

tensor([[35, 22],
        [73, 49]])

In [70]:
v1 = torch.tensor([1,2,3])
v2 = torch.tensor([5,6,7])
v1.dot(v2)

tensor(38)

In [72]:
torch.transpose(g, 0, 1)

tensor([[ 7,  4, 12],
        [ 7,  2,  7]])

In [76]:
h = torch.randint(size=(3,3),low=1, high=15,dtype=torch.float64)
h

tensor([[13., 14.,  7.],
        [ 2.,  9., 11.],
        [14., 10.,  5.]], dtype=torch.float64)

In [ ]:
torch.det(h) #determinant

tensor(429.0000, dtype=torch.float64)

In [ ]:
torch.inverse(h) #inverse

tensor([[-0.1515,  0.0000,  0.2121],
        [ 0.3357, -0.0769, -0.3007],
        [-0.2471,  0.1538,  0.2075]], dtype=torch.float64)

**5. Comparison Operations**

In [79]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[4, 2, 7],
        [1, 1, 5]])
tensor([[4, 4, 1],
        [1, 2, 4]])


In [80]:
# greater than
print(i > j)
# less than
print(i < j)
# equal to
print(i == j)
# not equal to
print(i != j)
# greater than equal to
print(i >= j)

tensor([[False, False,  True],
        [False, False,  True]])
tensor([[False,  True, False],
        [False,  True, False]])
tensor([[ True, False, False],
        [ True, False, False]])
tensor([[False,  True,  True],
        [False,  True,  True]])
tensor([[ True, False,  True],
        [ True, False,  True]])


**6. Special Functions**

In [81]:
k = torch.randint(size=(2,2),low=1, high=15, dtype=torch.float64)
k

tensor([[12.,  7.],
        [ 6.,  3.]], dtype=torch.float64)

In [82]:
#log
torch.log(k)

tensor([[2.4849, 1.9459],
        [1.7918, 1.0986]], dtype=torch.float64)

In [83]:
#sqrt
torch.sqrt(k)

tensor([[3.4641, 2.6458],
        [2.4495, 1.7321]], dtype=torch.float64)

In [84]:
#exp
torch.exp(k)

tensor([[1.6275e+05, 1.0966e+03],
        [4.0343e+02, 2.0086e+01]], dtype=torch.float64)

In [85]:
#relu
torch.relu(k)

tensor([[12.,  7.],
        [ 6.,  3.]], dtype=torch.float64)

In [86]:
#sigmoid
torch.sigmoid(k)

tensor([[1.0000, 0.9991],
        [0.9975, 0.9526]], dtype=torch.float64)

In [87]:
#tanh
torch.tanh(k)

tensor([[1.0000, 1.0000],
        [1.0000, 0.9951]], dtype=torch.float64)

In [90]:
#softmax
torch.softmax(k, 0)

tensor([[0.9975, 0.9820],
        [0.0025, 0.0180]], dtype=torch.float64)

**7. Inplace operations**

In [91]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.5224, 0.4175, 0.0340],
        [0.9157, 0.3079, 0.6269]])
tensor([[0.8277, 0.6594, 0.0887],
        [0.4890, 0.5887, 0.7340]])


In [92]:
m.add_(n)
print(m)
print(n)

tensor([[1.3501, 1.0769, 0.1227],
        [1.4047, 0.8966, 1.3610]])
tensor([[0.8277, 0.6594, 0.0887],
        [0.4890, 0.5887, 0.7340]])


In [93]:
m.relu_()
print(m)

tensor([[1.3501, 1.0769, 0.1227],
        [1.4047, 0.8966, 1.3610]])


**Copying a Tensor**

In [94]:
a = torch.rand(2,3)
a

tensor([[0.8497, 0.9112, 0.4847],
        [0.9436, 0.3904, 0.2499]])

In [95]:
b = a

In [96]:
b

tensor([[0.8497, 0.9112, 0.4847],
        [0.9436, 0.3904, 0.2499]])

In [97]:
a[0][0] = 0.1234

In [98]:
b

tensor([[0.1234, 0.9112, 0.4847],
        [0.9436, 0.3904, 0.2499]])

In [99]:
id(a), id(b)

(3036972591024, 3036972591024)

In [100]:
b = a.clone()

In [101]:
a[0][0] = 1.345

In [102]:
print(a)
print(b)

tensor([[1.3450, 0.9112, 0.4847],
        [0.9436, 0.3904, 0.2499]])
tensor([[0.1234, 0.9112, 0.4847],
        [0.9436, 0.3904, 0.2499]])


In [103]:
id(a), id(b)

(3036972591024, 3036971766624)